server:
  port: 8080

spring:
  application:
    name: product
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071
  datasource:
    url: jdbc:postgresql://localhost:5432/ProductDB
    username: 'postgres'
    password: 'china.123'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    defer-datasource-initialization: true
  sql:
    init:
      mode: always